services:
  postgres:
    image: postgres:16
    container_name: griffiths-crm-db
    environment:
      POSTGRES_USER: griffiths_crm_app
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: griffiths_crm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
